import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import { Raleway } from 'next/font/google';
import SessionProvider from './components/SessionProvider/SessionProvider';
import './globals.css';

const inter = Raleway({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Discord App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={await getServerSession()}>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
